spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/msa_exam
    username: root
    password: password

server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/